##
##  HUDS -- Head-Up-Display Server (HUDS)
##  Copyright (c) 2022 Dr. Ralf S. Engelschall <rse@engelschall.com>
##
##  Permission is hereby granted, free of charge, to any person obtaining
##  a copy of this software and associated documentation files (the
##  "Software"), to deal in the Software without restriction, including
##  without limitation the rights to use, copy, modify, merge, publish,
##  distribute, sublicense, and/or sell copies of the Software, and to
##  permit persons to whom the Software is furnished to do so, subject to
##  the following conditions:
##
##  The above copyright notice and this permission notice shall be included
##  in all copies or substantial portions of the Software.
##
##  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
##  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
##  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
##  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
##  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
##  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
##  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
##

huds:

    api:        "mqtt"                       # API  to use (currently MQTT only)
    url:        "wss://pad.huds.io/mqtt/"    # URL  of MQTT broker
    peer:       "live-sender"                # name of MQTT peer

ui:
    theme:      "dark"                       # select dark or light theme
    language:   "en"                         # select english (en) or german (de) language
    hints:      true                         # show UI control hints
    debug:      false                        # show debug information in console

    title1:     "HUDS"                       # title text (part 1/2)
    title2:     "Pad"                        # title text (part 2/2)

    title:      true                         # show common title text (and button for about)
    about:      true                         # show common about area
    info:       true                         # show common info/status area
    attendees:  true                         # show common attendees indicator
    traffic:    true                         # show common traffic indicator
    online:     true                         # show common online indicator
    qrcode:     true                         # show common qrcode button and area
    config:     true                         # show common config button

    token:      true                         # show login token input
    connect:    true                         # show login connect button
    slogan:     true                         # show login slogan text

    disconnect: true                         # show interaction disconnect button
    name:       true                         # show interaction name field (of message)
    message:    true                         # show interaction message area
    vote:       true                         # show interaction vote area
    feedback:   true                         # show interaction feedback area
    feeling:    true                         # show interaction feeling area

    anonymous:  true                         # whether anonymous (with empty name) messages are allowed

custom:

    css:        false
    js:         false

